---
- name: Copy MetalLB ConfigMap manifest
  ansible.builtin.template:
    src: metallb-configmap.yml.j2
    dest: /tmp/metallb-configmap.yaml
    mode: "0644"

- name: Apply MetalLB manifests
  ansible.builtin.command: k3s kubectl apply -f https://raw.githubusercontent.com/metallb/metallb/v0.14.5/config/manifests/metallb-native.yaml
  changed_when: false

- name: Wait for MetalLB controller deployment to be available
  ansible.builtin.command: k3s kubectl -n metallb-system wait deployment/controller --for=condition=Available=True --timeout=120s
  register: metallb_wait
  changed_when: false
  failed_when: metallb_wait.rc != 0

- name: Wait for MetalLB webhook service pod to be ready
  ansible.builtin.command: k3s kubectl -n metallb-system wait --for=condition=Ready --timeout=120s pod -l app=metallb,component=controller
  changed_when: false
  failed_when: false

- name: Wait for MetalLB webhook-service endpoints to exist
  ansible.builtin.command: k3s kubectl -n metallb-system get endpoints metallb-webhook-service
  register: webhook_ep
  retries: 10
  delay: 5
  until: webhook_ep.rc == 0 and 'None' not in webhook_ep.stdout
  changed_when: false

- name: Apply MetalLB ConfigMap
  ansible.builtin.command: k3s kubectl apply -f /tmp/metallb-configmap.yaml
  changed_when: false