---
- name: Create argocd namespace
  command: kubectl create namespace argocd --dry-run=client -o yaml | kubectl apply -f -
  args:
    creates: /var/lib/rancher/k3s/server/manifests/argocd-ns.yaml
  tags:
    - argocd
    - install

- name: Install ArgoCD
  command: kubectl apply -n argocd -f https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
  register: argocd_install
  retries: 3
  delay: 10
  until: argocd_install.rc == 0
  tags:
    - argocd
    - install

- name: Copy service patch file
  copy:
    src: argocd-server-svc-patch.yaml
    dest: /tmp/argocd-server-svc-patch.yaml
    mode: '0644'
  when: argocd_install.rc == 0
  tags:
    - argocd
    - config

- name: Patch ArgoCD service to use LoadBalancer
  command: kubectl patch svc argocd-server -n argocd --patch-file /tmp/argocd-server-svc-patch.yaml
  when: argocd_install.rc == 0
  register: patch_result
  retries: 3
  delay: 5
  until: patch_result.rc == 0
  ignore_errors: true
  tags:
    - argocd
    - config

- name: Wait for ArgoCD to be ready
  command: kubectl -n argocd wait --for=condition=available deployment/argocd-server --timeout=300s
  register: wait_result
  retries: 6
  delay: 10
  until: wait_result.rc == 0
  ignore_errors: true
  tags:
    - argocd
    - wait
